server:
  applicationConnectors:
    - type: http
      port: ${PORT}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT}

swagger:
  resourcePackage: com.example.helloworld.resources

rmq:
  brokers:
    - host: ${RMQ_HOST}
      port: ${RMQ_PORT}
  userName: ${RMQ_USERNAME}
  password: ${RMQ_PASSSWORD}
  threadPoolSize: ${RMQ_THREAD_POOL_SIZE}
  virtualHost: ${RMQ_VIRTUAL_HOST}

actors:
  STRAVA_WEBHOOKS:
    exchange: strava_webhooks
    delayed: false
    prefix: strava
    concurrency: 1
    prefetchCount: 1
    retryConfig:
      type: COUNT_LIMITED_EXPONENTIAL_BACKOFF
      maxAttempts: 6
      multipier: 50
      maxTimeBetweenRetries: 30s